server:
  port: 7245
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RoomAppoint?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 10000MB
      max-file-size: 10024MB

  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mail:
    host: smtp.163.com              # 163 的 SMTP 服务器地址
    port: 465                       # SMTP SSL端口，建议用465
    username: 15163322850@163.com       # 发件人邮箱
    password: AEqDpJjBc85vxbZQ             # 不是登录密码，而是授权码
    protocol: smtp                 # 使用 SSL 协议
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true


mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.web.entity
  global-config:
    db-config:
      table-prefix:  # 留空，表示不加前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG



