server:
  port: 7245
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RoomAppoint?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mail:
    host: smtp.163.com
    port: 465
    username: smallvnb@163.com
    password: CCS6fQ42U4CQiAJs
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.web.entity
  global-config:
    db-config:
      table-prefix:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG

app:
  upload:
    path: ./uploads
    url-prefix: http://localhost:7245